apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  selector:
    app: CICD
  type: NodePort
  ports:
          - port: 80
            targetPort: 8080 
            nodePort: 30045
